#!/bin/bash

# Function to pad day with leading zero if less than 10
pad_day() {
    printf "%02d" $1
}

# Check if an argument is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: ./run <day>"
    exit 1
fi

# Pad the day with leading zero if necessary
DAY=$(pad_day $1)

# compile and run the program
tsc
node dist/days/day$DAY.js
